spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/task_manager}
    username: ${DATABASE_USERNAME:task_manager}
    password: ${DATABASE_PASSWORD:task_manager}
  jpa:
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET:dGFzay1tYW5hZ2VyLWxvY2FsLWRldmVsb3BtZW50LXNlY3JldC1rZXktMzItYnl0ZXM=}
  bootstrap:
    enabled: ${BOOTSTRAP_ENABLED:true}

logging:
  level:
    root: INFO
    com.caiowilquer.taskmanager: DEBUG
